import { Book } from '@/types/book';

export const books: Book[] = [
  {
    title: 'Halloween Party',
    author: 'Agatha Christie',
    description: 'A classic mystery novel featuring Hercule Poirot investigating a murder at a Halloween party.',
    image: 'https://covers.openlibrary.org/b/olid/OL7666500M-L.jpg',
    genre: 'Mystery',
  },
  {
    title: 'The Silent Patient',
    author: 'Alex Michaelides',
    description: 'A psychological thriller about a woman who refuses to speak after allegedly murdering her husband.',
    image: 'https://covers.openlibrary.org/b/olid/OL59645497M-L.jpg',
    genre: 'Thriller',
  },
  {
    title: 'Dark Matter',
    author: 'Blake Crouch',
    description: 'A mind-bending science fiction thriller exploring parallel universes and the multiverse.',
    image: 'https://covers.openlibrary.org/b/olid/OL27222609M-L.jpg',
    genre: 'Science Fiction',
  },
  {
    title: 'Recursion',
    author: 'Blake Crouch',
    description: 'A time-travel thriller where memories can be recorded and replayed, leading to dangerous consequences.',
    image: 'https://covers.openlibrary.org/b/olid/OL29825479M-L.jpg',
    genre: 'Thriller',
  },
  {
    title: 'The Maidens',
    author: 'Alex Michaelides',
    description: 'A psychological thriller involving Greek mythology and a secret society at Cambridge University.',
    image: 'https://covers.openlibrary.org/b/olid/OL28215148M-L.jpg',
    genre: 'Thriller',
  },
  {
    title: 'Wrong Place Wrong Time',
    author: 'Gillian McAllister',
    description: 'A mother witnesses her son commit a murder and wakes up the day before, reliving time backwards.',
    image: 'https://covers.openlibrary.org/b/olid/OL36929999M-L.jpg',
    genre: 'Thriller',
  },
  {
    title: 'A Thousand Boy Kisses',
    author: 'Tillie Cole',
    description: 'A heart-wrenching romance about love, loss, and the power of memories.',
    image: 'https://covers.openlibrary.org/b/olid/OL35687633M-L.jpg',
    genre: 'Romance',
  },
  {
    title: 'Verity',
    author: 'Colleen Hoover',
    description: 'A psychological thriller about a struggling writer who discovers dark secrets in another author\'s manuscript.',
    image: 'https://covers.openlibrary.org/b/olid/OL39128605M-L.jpg',
    genre: 'Thriller',
  },
  {
    title: 'The Housemaid',
    author: 'Freida McFadden',
    description: 'A domestic thriller about a nanny who becomes entangled in her employer\'s dark secrets.',
    image: 'https://covers.openlibrary.org/b/olid/OL48263046M-L.jpg',
    genre: 'Thriller',
  },
  {
    title: 'The Housemaid\'s Secret',
    author: 'Freida McFadden',
    description: 'The sequel to The Housemaid, revealing more twists and secrets.',
    image: 'https://covers.openlibrary.org/b/olid/OL48185910M-L.jpg',
    genre: 'Thriller',
  },
  {
    title: 'Black Suits You',
    author: 'Novoneel Chakraborty',
    description: 'A romantic thriller involving corporate espionage and unexpected alliances.',
    image: 'https://covers.openlibrary.org/b/olid/OL29340030M-L.jpg',
    genre: 'Thriller',
  },
  {
    title: 'The Housemaid is Watching',
    author: 'Freida McFadden',
    description: 'Another installment in the Housemaid series, full of suspense and surprises.',
    image: 'https://covers.openlibrary.org/b/olid/OL50722099M-L.jpg',
    genre: 'Thriller',
  },
  {
    title: 'Never Lie',
    author: 'Freida McFadden',
    description: 'A psychological thriller about a psychiatrist who uncovers terrifying truths.',
    image: 'https://covers.openlibrary.org/b/olid/OL50648604M-L.jpg',
    genre: 'Thriller',
  },
  {
    title: 'The Boyfriend',
    author: 'Freida McFadden',
    description: 'A domestic thriller exploring jealousy, secrets, and betrayal.',
    image: 'https://covers.openlibrary.org/b/olid/OL53362967M-L.jpg',
    genre: 'Thriller',
  },
  {
    title: 'The Inmate',
    author: 'Freida McFadden',
    description: 'A story of revenge and justice set in a prison environment.',
    image: 'https://covers.openlibrary.org/b/olid/OL50637517M-L.jpg',
    genre: 'Thriller',
  },
  {
    title: 'None of This is True',
    author: 'Lisa Jewell',
    description: 'A psychological thriller about a podcaster who becomes obsessed with her subject.',
    image: 'https://covers.openlibrary.org/b/olid/OL49583668M-L.jpg',
    genre: 'Thriller',
  },
  {
    title: 'The Midnight Library',
    author: 'Matt Haig',
    description: 'A novel about infinite possibilities and the life choices we make.',
    image: 'https://covers.openlibrary.org/b/olid/OL30182151M-L.jpg',
    genre: 'Fiction',
  },
];
